# TYPE  DATABASE  USER      ADDRESS   METHOD
# O superusuário só entra pelo socket local, de dentro do contêiner.
local   all       all                 scram-sha-256
host    all       postgres  all       reject
host    all       all       samehost  scram-sha-256
host    all       all       samenet   scram-sha-256
